/*!
* © by Sitsanlis Ilias
* This notice shall be included in all copies or substantial portions of the Software.
* Creative Commons 4.0/CC BY - NC - SA 4.0. 
*/

helpText.text = "Με την συγκεκριμένη προσομοίωση μπορούμε να μελετήσουμε το θεώρημα του Torricelli. Έχουμε την δυνατότητα να μεταβάλλουμε το ύψος του νερού που υπάρχει στο δοχείο, την απόσταση της οπής από την βάση του δοχείου, το ύψος στο οποίο βρίσκεται το δοχείο (σύροντας το έδαφος ή το νερό), το εμβαδόν της οπής και την εξωτερική πίεση."

var canvas,stage,self,percent=.79,marginVarNumber=155,marginVar=marginVarNumber,controlBoxContainer,PI=Math.PI,toDeg=180/PI,toRad=PI/180,X0=160,Y0=210,t=0,dt=.1,dtInitial=dt,dtSlow=dt,factor=.5,playMovie=!1,framePlay=!1,xScale=30,yScale=-xScale,FScale=1E-4,vectorScale=1,valuesText=new createjs.Text("","12px Trebuchet MS");valuesText.set({x:360,y:383,textAlign:"center"});
var infoText=new createjs.Text("A = 1 m\u00b2","12px Trebuchet MS"),fpsLabel=new createjs.Text("-- fps","10px Trebuchet MS","#000000"),A1=1,A0=.01,\u03c1=1E3,g=10,H,Hi=5,Hg=5,Hbox=5.2,D=4,d=10*A0,h=0,h1=h-d/2,h2=Hi-h-d/2,Pex=1E5,Patm=1E5,v0,aa,bb,tStop,liquid=new createjs.Shape;liquid.name="liquid";liquid.addEventListener("mousedown",mouseDownGen);liquid.addEventListener("pressup",pressUpGen);liquid.mouseChildren=!1;
var box=new createjs.Shape,table=new createjs.Shape,tube=new createjs.Shape,ground=new createjs.Shape;ground.name="ground";ground.addEventListener("mousedown",mouseDownGen);ground.addEventListener("pressup",pressUpGen);ground.mouseChildren=!1;var cloneGraphs=new createjs.Container;cloneGraphs.alpha=.6;var hDistance=new createjs.Container,HDistance=new createjs.Container,HgDistance=new createjs.Container,piston=new createjs.Shape,FVec=createVector("#009900",!1,!1),xAxis=new createjs.Container;
function init(){stage=new createjs.Stage(document.getElementById("demoCanvas"));createjs.Touch.enable(stage);stage.enableMouseOver();canvas=document.getElementById("demoCanvas");self=stage;controlBoxContainer=new createjs.Container;self.addChild(controlBoxContainer);var a=new createjs.DOMElement("foo");controlBoxContainer.addChild(a);controlBoxContainer.x=5;controlBoxContainer.y=3.5;controlBoxContainer.alpha=.9;stage.addChild(cloneGraphs);stage.addChild(ground);stage.addChild(table);stage.addChild(fpsLabel);
fpsLabel.x=685;fpsLabel.y=405;stage.addChild(valuesText);stage.addChild(liquid);stage.addChild(box);stage.addChild(tube);stage.addChild(hDistance);stage.addChild(HDistance);stage.addChild(HgDistance);stage.addChild(piston);stage.addChild(FVec);stage.addChild(xAxis);stage.addChild(infoText);createRegister();stage.addChild(\u03a8);addFunction();showHideVariables();handleComplete();initialize();createjs.Ticker.timingMode=createjs.Ticker.RAF;createjs.Ticker.addEventListener("tick",tick);canvas.style.visibility=
"visible";document.getElementById("variables").style.visibility="visible"}function initialize(){infoText.set({x:100,y:Y0+13,textAlign:"center"});liquid.set({x:X0-D*xScale,y:Y0});box.set({x:X0-D*xScale,y:Y0});table.set({x:X0,y:Y0});tube.set({x:X0,y:Y0});piston.set({x:X0,y:Y0});FVec.set({x:X0-D*xScale/2,rotation:90});xAxis.set({x:X0,y:Y0-Hg*yScale});xAxis.xAxisCreate(0,17.5,1,xScale);drawGraoud();restart()}
function restart(){isOk||stage.removeAllChildren();t=0;d=10*A0;lastValidH=H=Hi;h2=h;h1=Hi-h-d;hDistance.drawDistance("#333",X0,Y0+h2*yScale,X0,Y0,20,h2.toFixed(1)+" m");1E5<Pex?drawPiston():piston.graphics.clear();FVec.setScaleX((Pex-Patm)*FScale);aa=2*g*A0*A0/(A1*A1-A0*A0);bb=2*A0*A0*(Pex-Patm)/(\u03c1*(A1*A1-A0*A0));tStop=2*(Math.sqrt(aa*(Hi-h2)+bb)-Math.sqrt(bb))/aa;drawBox();drawTable();positions()}
function tick(a){playMovie&&(framePlay&&(framePlay=playMovie=!1),0<=t+dt&&(!isNaN(tStop)&&0<tStop?(t+=dt,t>=tStop&&(t=tStop,$("#play").trigger("click")),H=Ht(t)):$("#play").trigger("click"),positions()))}
function positions(){var a=Math.sqrt(2*(Hg+h2)/g);tube.graphics.clear();H>h2?(v0=-(A1/A0)*fr(t,H),drawParabole(t),valuesText.text="t = "+t.toFixed(1)+" s, \u0397 = "+H.toFixed(2)+" m, v\u2080 = "+v0.toFixed(1)+" m/s, Hg = "+(Hg+h2).toFixed(1)+" m, x = "+(v0*a).toFixed(1)+" m"):valuesText.text="t = "+t.toFixed(1)+" s, \u0397 = "+H.toFixed(2)+" m";liquid.graphics.clear().f("#9999ff").r(0,H*yScale,D*xScale,-H*yScale);piston.y=Y0+H*yScale;FVec.y=Y0+H*yScale-(Pex-Patm)*FScale-5;fpsLabel.text=Math.round(createjs.Ticker.getMeasuredFPS())+
" fps";stage.update()}function drawBox(){box.graphics.clear().ss(2).s("#333").mt(0,Hbox*yScale).lt(0,0).lt(D*xScale,0).lt(D*xScale,h2*yScale).mt(D*xScale,(Hi-h1)*yScale).lt(D*xScale,Hbox*yScale);HDistance.drawDistance("#333",40,Y0+Hi*yScale,40,Y0,20,Hi.toFixed(1)+" m")}function drawPiston(){piston.graphics.clear().ss(1).s("#333").mt(0,0).lt(-D*xScale,0).lt(-D*xScale,-5).lt(0,-5).lt(0,0)}
function drawTable(){var a=10<Hg*xScale?10:Hg*xScale;table.graphics.clear().ss(2).s("#333").mt(0,-Hg*yScale).lt(0,0).lt(-D*xScale,0).lt(-D*xScale,-Hg*yScale).lt(-D*xScale+10,-Hg*yScale).lt(-D*xScale+20,a).lt(-20,a).lt(-10,-Hg*yScale).cp();HgDistance.drawDistance("#333",40,Y0,40,Y0-Hg*yScale,20,Hg.toFixed(1)+" m")}
function drawGraoud(){var a=ground.graphics;a.clear();ground.y=Y0-Hg*yScale;a.f("#fff").r(0,0,720,20).endFill();a.setStrokeStyle(1);a.beginStroke("#aaa");for(i=0;720>=i;i+=5)a.mt(i,0).lt(i-10*.707,10*.707);a.setStrokeStyle(2);a.beginStroke("#aaa");a.mt(0,0).lt(720,0)}
function drawParabole(a){a=1/60;var b,c=Math.sqrt(2*(Hg+h2)/g);tube.graphics.clear().f("#9999ff").mt(0,h2*yScale);for(b=0;b<c;b+=a){var e=v0*b,f=h2-.5*g*b*b;tube.graphics.lt(e*xScale,f*yScale)}tube.graphics.lt(v0*c*xScale,(h2-.5*g*c*c)*yScale);var k=H>h2+d?Hi-h1:H;c=Math.sqrt(2*(Hg+k)/g);tube.graphics.lt(v0*c*xScale,-Hg*yScale);for(b=c;0<=b;b-=a)e=v0*b,f=k-.5*g*b*b,tube.graphics.lt(e*xScale,f*yScale);tube.graphics.lt(0,k*yScale);tube.graphics.endStroke();tube.graphics.cp()}
function rungeKutta(a,b){var c=fr(a,b),e=fr(a+dt/2,b+c*dt/2),f=fr(a+dt/2,b+e*dt/2),k=fr(a+dt,b+f*dt);return b+=dt*(c+2*e+2*f+k)/6}function fr(a,b){return-(A0/A1)*Math.sqrt((2*\u03c1*g*(b-h2)+2*(Pex-Patm))/(\u03c1*(1-A0/A1*(A0/A1))))}function Ht(a){a=Math.sqrt(aa*(Hi-h2)+bb)-.5*aa*a;return a=h2+(a*a-bb)/aa};